function seqs=configSeqs(data_path)

seqVTD={struct('name','soccer','path','/media/shi/Seagate Backup Plus Drive/VTB/Soccer/','startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','matrix','path','/media/shi/Seagate Backup Plus Drive/VTB/Matrix/','startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ironman','path','/media/shi/Seagate Backup Plus Drive/VTB/Ironman/','startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','deer','path','/media/shi/Seagate Backup Plus Drive/VTB/Deer/','startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skating1','path','/media/shi/Seagate Backup Plus Drive/VTB/Skating1/','startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','shaking','path','/media/shi/Seagate Backup Plus Drive/VTB/Shaking/','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer1','path','/media/shi/Seagate Backup Plus Drive/VTB/Singer1/','startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer2','path','/media/shi/Seagate Backup Plus Drive/VTB/Singer2/','startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqIVT={struct('name','carDark','path','/media/shi/Seagate Backup Plus Drive/VTB/CarDark/','startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','car4','path','/media/shi/Seagate Backup Plus Drive/VTB/Car4/','startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david','path','/media/shi/Seagate Backup Plus Drive/VTB/David/','startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david2','path','/media/shi/Seagate Backup Plus Drive/VTB/David2/','startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...    
    struct('name','sylvester','path','/media/shi/Seagate Backup Plus Drive/VTB/Sylvester/','startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','trellis','path','/media/shi/Seagate Backup Plus Drive/VTB/Trellis/','startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fish','path','/media/shi/Seagate Backup Plus Drive/VTB/Fish/','startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mhyang','path','/media/shi/Seagate Backup Plus Drive/VTB/Mhyang/','startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqOther={struct('name','coke','path','/media/shi/Seagate Backup Plus Drive/VTB/Coke/','startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','bolt','path','/media/shi/Seagate Backup Plus Drive/VTB/Bolt/','startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','boy','path','/media/shi/Seagate Backup Plus Drive/VTB/Boy/','startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dudek','path','/media/shi/Seagate Backup Plus Drive/VTB/Dudek/','startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','crossing','path','/media/shi/Seagate Backup Plus Drive/VTB/Crossing/','startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','couple','path','/media/shi/Seagate Backup Plus Drive/VTB/Couple/','startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football1','path','/media/shi/Seagate Backup Plus Drive/VTB/Football1/','startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging1','path','/media/shi/Seagate Backup Plus Drive/VTB/Jogging1/','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging2','path','/media/shi/Seagate Backup Plus Drive/VTB/Jogging2/','startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','doll','path','/media/shi/Seagate Backup Plus Drive/VTB/Doll/','startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','girl','path','/media/shi/Seagate Backup Plus Drive/VTB/Girl/','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking2','path','/media/shi/Seagate Backup Plus Drive/VTB/Walking2/','startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking','path','/media/shi/Seagate Backup Plus Drive/VTB/Walking/','startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fleetface','path','/media/shi/Seagate Backup Plus Drive/VTB/FleetFace/','startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman1','path','/media/shi/Seagate Backup Plus Drive/VTB/Freeman1/','startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman3','path','/media/shi/Seagate Backup Plus Drive/VTB/Freeman3/','startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman4','path','/media/shi/Seagate Backup Plus Drive/VTB/Freeman4/','startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david3','path','/media/shi/Seagate Backup Plus Drive/VTB/David3/','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jumping','path','/media/shi/Seagate Backup Plus Drive/VTB/Jumping/','startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','carScale','path','/media/shi/Seagate Backup Plus Drive/VTB/CarScale/','startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skiing','path','/media/shi/Seagate Backup Plus Drive/VTB/Skiing/','startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dog1','path','/media/shi/Seagate Backup Plus Drive/VTB/Dog1/','startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','suv','path','/media/shi/Seagate Backup Plus Drive/VTB/Suv/','startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','motorRolling','path','/media/shi/Seagate Backup Plus Drive/VTB/MotorRolling/','startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mountainBike','path','/media/shi/Seagate Backup Plus Drive/VTB/MountainBike/','startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... 
    struct('name','lemming','path','/media/shi/Seagate Backup Plus Drive/VTB/Lemming/','startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','liquor','path','/media/shi/Seagate Backup Plus Drive/VTB/Liquor/','startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','woman','path','/media/shi/Seagate Backup Plus Drive/VTB/Woman/','startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc1','path','/media/shi/Seagate Backup Plus Drive/VTB/FaceOcc1/','startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc2','path','/media/shi/Seagate Backup Plus Drive/VTB/FaceOcc2/','startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','basketball','path','/media/shi/Seagate Backup Plus Drive/VTB/Basketball/','startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football','path','/media/shi/Seagate Backup Plus Drive/VTB/Football/','startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','subway','path','/media/shi/Seagate Backup Plus Drive/VTB/Subway/','startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...    
    struct('name','tiger1','path','/media/shi/Seagate Backup Plus Drive/VTB/Tiger1/','startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','tiger2','path','/media/shi/Seagate Backup Plus Drive/VTB/Tiger2/','startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

s = [seqIVT,seqVTD,seqOther];

% add proper path to datasets
data_path = [data_path 'OTB/'];
seqs = {};
for i = 1:length(s)
    name = s{i}.name;
    name(1) = name(1) - 32;
    path = [data_path name '/'];
    
    sf = s{i}.startFrame;
    ef = s{i}.endFrame;
    
    % if you splited the sequences by hand, uncomment the block
    % below
    
    if ~(sf == 1)
        delta = sf - 1;
        sf = 1;
        ef = ef - delta;
    end
    seqs{end+1} = struct('name',name,'path',path,'startFrame',sf,'endFrame',ef,'nz',4,'ext','jpg','init_rect', [0,0,0,0]);
end

end

