function trackers=configTrackers

% OTB trackers' configuration for Tracker Surveys
% @YuzheSHI, HUST, Computer Science
% Oct, 2019

trackersVIVID={};

trackers1={
    struct('name','CSK','namePaper','CSK'),...
    struct('name','DSST','namePaper','DSST'),...
    struct('name','KCF_LinearHog','namePaper','DCF'),...
    struct('name','KCF_GaussHog','namePaper','KCF'),...
    struct('name','KCF_LinearGray','namePaper','MOSSE'),...
    struct('name','SRDCF','namePaper','SRDCF'),...
    struct('name','SAMF','namePaper','SAMF'),...
    struct('name','CCOT','namePaper','CCOT'),...
    struct('name','ECO','namePaper','ECO')
    };

trackersEXE={};

trackers = [trackersVIVID,trackers1,trackersEXE];
